name: client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-backend

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0

      - name: setup java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: build and run tests
        run: ./gradlew build test